### ISSUE TITLE
Parse special characters

### ISSUE THREAD

**Issue by apcxiii** [kennellroxco/xlsxir#15]
Hi, I don't read special characters like ampersand; i.e. "http://domain.com?param1=aaa&param2=two
![screen shot 2016-04-17 at 7 37 54 pm](https://cloud.githubusercontent.com/assets/1149079/14591269/f0ed0098-04d3-11e6-84b9-06068f3e4962.png)
![screen shot 2016-04-17 at 7 38 05 pm](https://cloud.githubusercontent.com/assets/1149079/14591278/09a9de62-04d4-11e6-84dd-0604203ce1d5.png)

"

**Comment by kennellroxco** [comment]
Looking at it now. I'll let you know once I figure out the bug.

**Comment by kennellroxco** [comment]
The issue looks to be caused by the xml parsing library I'm using. It's parsing the URL string into two separate strings at the ampersand and my code is only picking up the first one. I'll work on a fix but it may take me a couple of days, depending on my work schedule. Thanks for pointing out this bug.

**Comment by kennellroxco** [comment]
I published a new version (0.0.3) to account for this issue. Please update your dependencies and try again. Let me know if you have any further issues.

**Comment by apcxiii** [comment]
Thank you :)
